version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
     - PUBSUB_EMULATOR_HOST=pubsub:8085
     - HOST=http://backend:8002
     - GOOGLE_APPLICATION_CREDENTIALS=stock-news-summarizer-2dd608c469eb.json
    ports:
      - '8002:8002'
  mysql:
    image: percona:5.7-centos
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=stock_news
    volumes:
        - './mysql/init.sql:/data/application/init.sql'
    ports:
      - '3307:3306'
  pubsub:
    build:
      context: ./pubsub
      dockerfile: ./Dockerfile
    ports:
      - "8085:8085"