version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - './backend:/usr/src/app'
    environment:
     - FLASK_APP=index.py
     - APP_PORT=8002
    ports:
      - '8002:8002'
  mysql:
    image: percona:5.7-centos
    container_name: mysql
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=stock_news
    volumes:
        - './mysql/init.sql:/data/application/init.sql'
    ports:
      - '3307:3306'
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CREATE_TOPICS=StockNewsTopic:1:1
    ports:
      - '29092:29092'
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'